- name: Apache playbook
  hosts: myservers
  become: true
  tasks:
    - name: Updating the package repo
      apt:
        update_cache: yes
    - name: Installing the apache server
      apt:
        name: apache2
        state: latest
